version: '3.3' # optional since v1.27.0
services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=meta
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5435:5432'
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    external: false
